#!/bin/sh

echo "[pre-commit check]"

echo -n "Checking code format with spotless: "
mvn spotless:check > /tmp/spotless.out 2>&1
RETURN_VALUE=$?
if [ $RETURN_VALUE -gt 0 ]
then
  echo "Please run 'mvn spotless:check' for more details or 'mvn spotless:apply' to automatically fix the violations."
fi
exit $RETURN_VALUE