#!/usr/bin/env bash

echo "[pre-commit check]"

if ! [ -x "$(command -v mvn)" ]; then
  echo -e 'Maven are not installed!'
  echo
  echo 'Please visit following site to download latest maven:'
  echo
  echo "  https://maven.apache.org/download.cgi"
  echo
  echo 'If you are sure that you have installed maven,'
  echo 'Please check whether your environment variables is being set properly.'
  exit 1
fi

mvn spotless:apply